function freezeStringLists<const T extends Record<string, readonly string[]>>(value: T): Readonly<T> {
	for (const list of Object.values(value)) Object.freeze(list);
	return Object.freeze(value);
}

export const MINI_CLI_OPTIONS = freezeStringLists({
	"": ["--version"],
	browser: ["--port", "--no-open"],
	task: [],
	"task create": [
		"--description",
		"--assignee",
		"--status",
		"--labels",
		"--priority",
		"--type",
		"--milestone",
		"--depends-on",
		"--ac",
		"--acceptance-criteria",
		"--plain",
	],
	"task list": [
		"--status",
		"--exclude-status",
		"--assignee",
		"--unassigned",
		"--milestone",
		"--priority",
		"--type",
		"--labels",
		"--search",
		"--ready",
		"--limit",
		"--sort",
		"--plain",
		"--json",
		"--watch",
	],
	search: ["--type", "--task-type", "--status", "--exclude-status", "--priority", "--limit", "--plain", "--json"],
	"task view": ["--plain", "--json"],
	"task edit": [
		"--title",
		"--description",
		"--assignee",
		"--status",
		"--label",
		"--priority",
		"--type",
		"--milestone",
		"--clear-milestone",
		"--plain",
		"--add-label",
		"--remove-label",
		"--clear-labels",
		"--ac",
		"--remove-ac",
		"--check-ac",
		"--uncheck-ac",
		"--acceptance-criteria",
		"--clear-ac",
		"--comment",
		"--comment-author",
		"--clear-deps",
		"--depends-on",
	],
	"task complete": [],
	doc: [],
	"doc create": ["--path", "--type", "--plain"],
	"doc update": ["--title", "--content", "--path", "--type", "--tags"],
	"doc list": ["--plain"],
	"doc search": ["--limit"],
	"doc view": ["--plain"],
	milestone: [],
	"milestone list": ["--show-completed", "--plain"],
	"milestone add": ["--description"],
	"milestone rename": ["--no-update-tasks"],
	"milestone remove": ["--task-handling", "--reassign-to"],
	mcp: [],
	"mcp start": ["--debug", "--cwd"],
} as const);

export const MINI_CLI_DESCRIPTIONS = Object.freeze({
	"": "mini-backlog.md - restricted CLI/MCP with the full browser interface",
	browser: "start the browser interface",
	task: "manage tasks",
	"task create": "create a task",
	"task list": "list tasks",
	search: "search tasks and documents",
	"task view": "view a task",
	"task edit": "edit a task",
	"task complete": "move a terminal-status task to completed",
	doc: "manage documents",
	"doc create": "create a document",
	"doc update": "update a document",
	"doc list": "list documents",
	"doc search": "search documents",
	"doc view": "view a document",
	milestone: "manage milestones",
	"milestone list": "list milestones",
	"milestone add": "add a milestone",
	"milestone rename": "rename a milestone",
	"milestone remove": "remove a milestone",
	mcp: "manage the MCP server",
	"mcp start": "start the restricted MCP server",
} as const);

export const MINI_MCP_TOOL_NAMES = Object.freeze([
	"task_create",
	"task_list",
	"task_search",
	"task_view",
	"task_edit",
	"task_complete",
	"document_list",
	"document_search",
	"document_view",
	"document_create",
	"document_update",
	"milestone_list",
	"milestone_add",
	"milestone_rename",
	"milestone_remove",
] as const);

export const MINI_TASK_CREATE_PROPERTIES = Object.freeze([
	"title",
	"description",
	"status",
	"priority",
	"type",
	"milestone",
	"labels",
	"assignee",
	"dependencies",
	"acceptanceCriteria",
] as const);
export const MINI_TASK_LIST_PROPERTIES = Object.freeze([
	"status",
	"type",
	"assignee",
	"unassigned",
	"milestone",
	"labels",
	"search",
	"ready",
	"limit",
] as const);
export const MINI_TASK_SEARCH_PROPERTIES = Object.freeze(["query", "status", "type", "priority", "limit"] as const);
export const MINI_TASK_EDIT_PROPERTIES = Object.freeze([
	"id",
	"title",
	"description",
	"status",
	"priority",
	"type",
	"milestone",
	"labels",
	"assignee",
	"dependencies",
	"commentsAppend",
	"commentAuthor",
	"acceptanceCriteriaSet",
	"acceptanceCriteriaAdd",
	"acceptanceCriteriaRemove",
	"acceptanceCriteriaCheck",
	"acceptanceCriteriaUncheck",
] as const);
export const MINI_TASK_SUMMARY_FIELDS = Object.freeze([
	"id",
	"title",
	"status",
	"type",
	"priority",
	"assignees",
	"labels",
	"milestone",
	"acceptanceCriteriaCompleted",
	"acceptanceCriteriaCount",
	"createdAt",
	"updatedAt",
] as const);
export const MINI_TASK_DETAIL_FIELDS = Object.freeze([
	...MINI_TASK_SUMMARY_FIELDS,
	"description",
	"dependencies",
	"acceptanceCriteria",
	"comments",
] as const);
export const MINI_TASK_SORT_FIELDS = Object.freeze(["priority", "id"] as const);
